[
  {
    id: "sv6-80",
    name: "Abra",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/80.png",
      large: "https://images.pokemontcg.io/sv6/80_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-142",
    name: "Accompanying Flute",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/142.png",
      large: "https://images.pokemontcg.io/sv6/142_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-122",
    name: "Aggron",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/122.png",
      large: "https://images.pokemontcg.io/sv6/122_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-137",
    name: "Aipom",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/137.png",
      large: "https://images.pokemontcg.io/sv6/137_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-82",
    name: "Alakazam",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/82.png",
      large: "https://images.pokemontcg.io/sv6/82_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-138",
    name: "Ambipom",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/138.png",
      large: "https://images.pokemontcg.io/sv6/138_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-126",
    name: "Applin",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/126.png",
      large: "https://images.pokemontcg.io/sv6/126_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-185",
    name: "Applin",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/185.png",
      large: "https://images.pokemontcg.io/sv6/185_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-17",
    name: "Applin",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/17.png",
      large: "https://images.pokemontcg.io/sv6/17_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-5",
    name: "Ariados",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/5.png",
      large: "https://images.pokemontcg.io/sv6/5_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-120",
    name: "Aron",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/120.png",
      large: "https://images.pokemontcg.io/sv6/120_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-74",
    name: "Bellibolt",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/74.png",
      large: "https://images.pokemontcg.io/sv6/74_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-201",
    name: "Blissey ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/201.png",
      large: "https://images.pokemontcg.io/sv6/201_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-134",
    name: "Blissey ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/134.png",
      large: "https://images.pokemontcg.io/sv6/134_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-216",
    name: "Bloodmoon Ursaluna ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Special Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/216.png",
      large: "https://images.pokemontcg.io/sv6/216_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-141",
    name: "Bloodmoon Ursaluna ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/141.png",
      large: "https://images.pokemontcg.io/sv6/141_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-222",
    name: "Bloodmoon Ursaluna ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Hyper Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/222.png",
      large: "https://images.pokemontcg.io/sv6/222_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-202",
    name: "Bloodmoon Ursaluna ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/202.png",
      large: "https://images.pokemontcg.io/sv6/202_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-166",
    name: "Boomerang Energy",
    supertype: "Energy",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/166.png",
      large: "https://images.pokemontcg.io/sv6/166_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-118",
    name: "Brute Bonnet",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/118.png",
      large: "https://images.pokemontcg.io/sv6/118_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-223",
    name: "Buddy-Buddy Poffin",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Hyper Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/223.png",
      large: "https://images.pokemontcg.io/sv6/223_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-143",
    name: "Bug Catching Set",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/143.png",
      large: "https://images.pokemontcg.io/sv6/143_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-144",
    name: "Caretaker",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/144.png",
      large: "https://images.pokemontcg.io/sv6/144_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-203",
    name: "Caretaker",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/203.png",
      large: "https://images.pokemontcg.io/sv6/203_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-145",
    name: "Carmine",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/145.png",
      large: "https://images.pokemontcg.io/sv6/145_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-217",
    name: "Carmine",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Special Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/217.png",
      large: "https://images.pokemontcg.io/sv6/217_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-204",
    name: "Carmine",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/204.png",
      large: "https://images.pokemontcg.io/sv6/204_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-38",
    name: "Chandelure",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/38.png",
      large: "https://images.pokemontcg.io/sv6/38_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-133",
    name: "Chansey",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/133.png",
      large: "https://images.pokemontcg.io/sv6/133_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-187",
    name: "Chansey",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/187.png",
      large: "https://images.pokemontcg.io/sv6/187_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-39",
    name: "Chi-Yu",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/39.png",
      large: "https://images.pokemontcg.io/sv6/39_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-31",
    name: "Chimchar",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/31.png",
      large: "https://images.pokemontcg.io/sv6/31_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-85",
    name: "Chimecho",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/85.png",
      large: "https://images.pokemontcg.io/sv6/85_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-179",
    name: "Chimecho",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/179.png",
      large: "https://images.pokemontcg.io/sv6/179_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-79",
    name: "Clefable",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/79.png",
      large: "https://images.pokemontcg.io/sv6/79_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-78",
    name: "Clefairy",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/78.png",
      large: "https://images.pokemontcg.io/sv6/78_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-146",
    name: "Community Center",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/146.png",
      large: "https://images.pokemontcg.io/sv6/146_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-105",
    name: "Conkeldurr",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/105.png",
      large: "https://images.pokemontcg.io/sv6/105_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-147",
    name: "Cook",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/147.png",
      large: "https://images.pokemontcg.io/sv6/147_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-112",
    name: "Cornerstone Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/112.png",
      large: "https://images.pokemontcg.io/sv6/112_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-215",
    name: "Cornerstone Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Special Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/215.png",
      large: "https://images.pokemontcg.io/sv6/215_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-199",
    name: "Cornerstone Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/199.png",
      large: "https://images.pokemontcg.io/sv6/199_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-47",
    name: "Corphish",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/47.png",
      large: "https://images.pokemontcg.io/sv6/47_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-58",
    name: "Cramorant",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/58.png",
      large: "https://images.pokemontcg.io/sv6/58_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-176",
    name: "Cramorant",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/176.png",
      large: "https://images.pokemontcg.io/sv6/176_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-48",
    name: "Crawdaunt",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/48.png",
      large: "https://images.pokemontcg.io/sv6/48_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-35",
    name: "Darmanitan",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/35.png",
      large: "https://images.pokemontcg.io/sv6/35_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-34",
    name: "Darumaka",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/34.png",
      large: "https://images.pokemontcg.io/sv6/34_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-127",
    name: "Dipplin",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/127.png",
      large: "https://images.pokemontcg.io/sv6/127_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-18",
    name: "Dipplin",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/18.png",
      large: "https://images.pokemontcg.io/sv6/18_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-170",
    name: "Dipplin",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/170.png",
      large: "https://images.pokemontcg.io/sv6/170_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-200",
    name: "Dragapult ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/200.png",
      large: "https://images.pokemontcg.io/sv6/200_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-130",
    name: "Dragapult ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/130.png",
      large: "https://images.pokemontcg.io/sv6/130_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-129",
    name: "Drakloak",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/129.png",
      large: "https://images.pokemontcg.io/sv6/129_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-128",
    name: "Dreepy",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/128.png",
      large: "https://images.pokemontcg.io/sv6/128_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-139",
    name: "Ducklett",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/139.png",
      large: "https://images.pokemontcg.io/sv6/139_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-135",
    name: "Eevee",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/135.png",
      large: "https://images.pokemontcg.io/sv6/135_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-188",
    name: "Eevee",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/188.png",
      large: "https://images.pokemontcg.io/sv6/188_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-69",
    name: "Emolga",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/69.png",
      large: "https://images.pokemontcg.io/sv6/69_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-180",
    name: "Enamorus",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/180.png",
      large: "https://images.pokemontcg.io/sv6/180_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-93",
    name: "Enamorus",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/93.png",
      large: "https://images.pokemontcg.io/sv6/93_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-148",
    name: "Enhanced Hammer",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/148.png",
      large: "https://images.pokemontcg.io/sv6/148_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-224",
    name: "Enhanced Hammer",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Hyper Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/224.png",
      large: "https://images.pokemontcg.io/sv6/224_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-132",
    name: "Farfetch'd",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/132.png",
      large: "https://images.pokemontcg.io/sv6/132_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-84",
    name: "Farigiraf",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/84.png",
      large: "https://images.pokemontcg.io/sv6/84_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-49",
    name: "Feebas",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/49.png",
      large: "https://images.pokemontcg.io/sv6/49_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-149",
    name: "Festival Grounds",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/149.png",
      large: "https://images.pokemontcg.io/sv6/149_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-96",
    name: "Fezandipiti",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/96.png",
      large: "https://images.pokemontcg.io/sv6/96_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-59",
    name: "Finizen",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/59.png",
      large: "https://images.pokemontcg.io/sv6/59_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-86",
    name: "Flabébé",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/86.png",
      large: "https://images.pokemontcg.io/sv6/86_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-87",
    name: "Floette",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/87.png",
      large: "https://images.pokemontcg.io/sv6/87_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-88",
    name: "Florges",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/88.png",
      large: "https://images.pokemontcg.io/sv6/88_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-56",
    name: "Froakie",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/56.png",
      large: "https://images.pokemontcg.io/sv6/56_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-57",
    name: "Frogadier",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/57.png",
      large: "https://images.pokemontcg.io/sv6/57_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-174",
    name: "Froslass",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/174.png",
      large: "https://images.pokemontcg.io/sv6/174_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-53",
    name: "Froslass",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/53.png",
      large: "https://images.pokemontcg.io/sv6/53_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-83",
    name: "Girafarig",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/83.png",
      large: "https://images.pokemontcg.io/sv6/83_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-54",
    name: "Glaceon",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/54.png",
      large: "https://images.pokemontcg.io/sv6/54_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-52",
    name: "Glalie",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/52.png",
      large: "https://images.pokemontcg.io/sv6/52_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-108",
    name: "Glimmet",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/108.png",
      large: "https://images.pokemontcg.io/sv6/108_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-109",
    name: "Glimmora",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/109.png",
      large: "https://images.pokemontcg.io/sv6/109_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-44",
    name: "Goldeen",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/44.png",
      large: "https://images.pokemontcg.io/sv6/44_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-106",
    name: "Greninja ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/106.png",
      large: "https://images.pokemontcg.io/sv6/106_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-198",
    name: "Greninja ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/198.png",
      large: "https://images.pokemontcg.io/sv6/198_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-214",
    name: "Greninja ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Special Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/214.png",
      large: "https://images.pokemontcg.io/sv6/214_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-14",
    name: "Grookey",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/14.png",
      large: "https://images.pokemontcg.io/sv6/14_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-104",
    name: "Gurdurr",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/104.png",
      large: "https://images.pokemontcg.io/sv6/104_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-150",
    name: "Handheld Fan",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/150.png",
      large: "https://images.pokemontcg.io/sv6/150_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-151",
    name: "Hassel",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/151.png",
      large: "https://images.pokemontcg.io/sv6/151_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-205",
    name: "Hassel",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/205.png",
      large: "https://images.pokemontcg.io/sv6/205_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-107",
    name: "Hawlucha",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/107.png",
      large: "https://images.pokemontcg.io/sv6/107_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-40",
    name: "Hearthflame Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/40.png",
      large: "https://images.pokemontcg.io/sv6/40_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-212",
    name: "Hearthflame Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Special Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/212.png",
      large: "https://images.pokemontcg.io/sv6/212_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-192",
    name: "Hearthflame Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/192.png",
      large: "https://images.pokemontcg.io/sv6/192_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-123",
    name: "Heatran",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/123.png",
      large: "https://images.pokemontcg.io/sv6/123_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-71",
    name: "Heliolisk",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/71.png",
      large: "https://images.pokemontcg.io/sv6/71_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-177",
    name: "Heliolisk",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/177.png",
      large: "https://images.pokemontcg.io/sv6/177_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-70",
    name: "Helioptile",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/70.png",
      large: "https://images.pokemontcg.io/sv6/70_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-8",
    name: "Heracross",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/8.png",
      large: "https://images.pokemontcg.io/sv6/8_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-100",
    name: "Hisuian Arcanine",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/100.png",
      large: "https://images.pokemontcg.io/sv6/100_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-181",
    name: "Hisuian Growlithe",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/181.png",
      large: "https://images.pokemontcg.io/sv6/181_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-99",
    name: "Hisuian Growlithe",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/99.png",
      large: "https://images.pokemontcg.io/sv6/99_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-152",
    name: "Hyper Aroma",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "ACE SPEC Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/152.png",
      large: "https://images.pokemontcg.io/sv6/152_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-10",
    name: "Illumise",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/10.png",
      large: "https://images.pokemontcg.io/sv6/10_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-173",
    name: "Infernape",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/173.png",
      large: "https://images.pokemontcg.io/sv6/173_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-33",
    name: "Infernape",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/33.png",
      large: "https://images.pokemontcg.io/sv6/33_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-62",
    name: "Iron Bundle",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/62.png",
      large: "https://images.pokemontcg.io/sv6/62_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-19",
    name: "Iron Leaves",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/19.png",
      large: "https://images.pokemontcg.io/sv6/19_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-77",
    name: "Iron Thorns ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/77.png",
      large: "https://images.pokemontcg.io/sv6/77_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-196",
    name: "Iron Thorns ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/196.png",
      large: "https://images.pokemontcg.io/sv6/196_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-153",
    name: "Jamming Tower",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/153.png",
      large: "https://images.pokemontcg.io/sv6/153_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-46",
    name: "Jynx",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/46.png",
      large: "https://images.pokemontcg.io/sv6/46_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-81",
    name: "Kadabra",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/81.png",
      large: "https://images.pokemontcg.io/sv6/81_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-218",
    name: "Kieran",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Special Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/218.png",
      large: "https://images.pokemontcg.io/sv6/218_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-154",
    name: "Kieran",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/154.png",
      large: "https://images.pokemontcg.io/sv6/154_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-206",
    name: "Kieran",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/206.png",
      large: "https://images.pokemontcg.io/sv6/206_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-76",
    name: "Kilowattrel",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/76.png",
      large: "https://images.pokemontcg.io/sv6/76_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-184",
    name: "Lairon",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/184.png",
      large: "https://images.pokemontcg.io/sv6/184_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-121",
    name: "Lairon",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/121.png",
      large: "https://images.pokemontcg.io/sv6/121_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-37",
    name: "Lampent",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/37.png",
      large: "https://images.pokemontcg.io/sv6/37_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-155",
    name: "Lana's Aid",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/155.png",
      large: "https://images.pokemontcg.io/sv6/155_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-219",
    name: "Lana's Aid",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Special Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/219.png",
      large: "https://images.pokemontcg.io/sv6/219_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-207",
    name: "Lana's Aid",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/207.png",
      large: "https://images.pokemontcg.io/sv6/207_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-11",
    name: "Leafeon",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/11.png",
      large: "https://images.pokemontcg.io/sv6/11_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-167",
    name: "Legacy Energy",
    supertype: "Energy",
    set_name: "Twilight Masquerade",
    rarity: "ACE SPEC Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/167.png",
      large: "https://images.pokemontcg.io/sv6/167_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-36",
    name: "Litwick",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/36.png",
      large: "https://images.pokemontcg.io/sv6/36_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-156",
    name: "Love Ball",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/156.png",
      large: "https://images.pokemontcg.io/sv6/156_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-157",
    name: "Lucian",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/157.png",
      large: "https://images.pokemontcg.io/sv6/157_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-208",
    name: "Lucian",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/208.png",
      large: "https://images.pokemontcg.io/sv6/208_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-158",
    name: "Lucky Helmet",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/158.png",
      large: "https://images.pokemontcg.io/sv6/158_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-226",
    name: "Luminous Energy",
    supertype: "Energy",
    set_name: "Twilight Masquerade",
    rarity: "Hyper Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/226.png",
      large: "https://images.pokemontcg.io/sv6/226_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-67",
    name: "Luxio",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/67.png",
      large: "https://images.pokemontcg.io/sv6/67_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-68",
    name: "Luxray ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/68.png",
      large: "https://images.pokemontcg.io/sv6/68_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-195",
    name: "Luxray ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/195.png",
      large: "https://images.pokemontcg.io/sv6/195_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-191",
    name: "Magcargo ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/191.png",
      large: "https://images.pokemontcg.io/sv6/191_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-29",
    name: "Magcargo ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/29.png",
      large: "https://images.pokemontcg.io/sv6/29_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-114",
    name: "Mightyena",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/114.png",
      large: "https://images.pokemontcg.io/sv6/114_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-50",
    name: "Milotic",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/50.png",
      large: "https://images.pokemontcg.io/sv6/50_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-32",
    name: "Monferno",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/32.png",
      large: "https://images.pokemontcg.io/sv6/32_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-72",
    name: "Morpeko",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/72.png",
      large: "https://images.pokemontcg.io/sv6/72_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-95",
    name: "Munkidori",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/95.png",
      large: "https://images.pokemontcg.io/sv6/95_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-27",
    name: "Ninetales",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/27.png",
      large: "https://images.pokemontcg.io/sv6/27_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-101",
    name: "Nosepass",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/101.png",
      large: "https://images.pokemontcg.io/sv6/101_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-159",
    name: "Ogre's Mask",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/159.png",
      large: "https://images.pokemontcg.io/sv6/159_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-111",
    name: "Okidogi",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/111.png",
      large: "https://images.pokemontcg.io/sv6/111_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-60",
    name: "Palafin",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/60.png",
      large: "https://images.pokemontcg.io/sv6/60_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-61",
    name: "Palafin ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/61.png",
      large: "https://images.pokemontcg.io/sv6/61_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-193",
    name: "Palafin ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/193.png",
      large: "https://images.pokemontcg.io/sv6/193_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-92",
    name: "Palossand",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/92.png",
      large: "https://images.pokemontcg.io/sv6/92_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-209",
    name: "Perrin",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/209.png",
      large: "https://images.pokemontcg.io/sv6/209_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-160",
    name: "Perrin",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/160.png",
      large: "https://images.pokemontcg.io/sv6/160_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-220",
    name: "Perrin",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Special Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/220.png",
      large: "https://images.pokemontcg.io/sv6/220_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-12",
    name: "Phantump",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/12.png",
      large: "https://images.pokemontcg.io/sv6/12_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-175",
    name: "Phione",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/175.png",
      large: "https://images.pokemontcg.io/sv6/175_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-55",
    name: "Phione",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/55.png",
      large: "https://images.pokemontcg.io/sv6/55_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-168",
    name: "Pinsir",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/168.png",
      large: "https://images.pokemontcg.io/sv6/168_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-3",
    name: "Pinsir",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/3.png",
      large: "https://images.pokemontcg.io/sv6/3_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-41",
    name: "Poliwag",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/41.png",
      large: "https://images.pokemontcg.io/sv6/41_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-42",
    name: "Poliwhirl",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/42.png",
      large: "https://images.pokemontcg.io/sv6/42_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-43",
    name: "Poliwrath",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/43.png",
      large: "https://images.pokemontcg.io/sv6/43_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-20",
    name: "Poltchageist",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/20.png",
      large: "https://images.pokemontcg.io/sv6/20_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-21",
    name: "Poltchageist",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/21.png",
      large: "https://images.pokemontcg.io/sv6/21_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-171",
    name: "Poltchageist",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/171.png",
      large: "https://images.pokemontcg.io/sv6/171_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-113",
    name: "Poochyena",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/113.png",
      large: "https://images.pokemontcg.io/sv6/113_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-182",
    name: "Probopass",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/182.png",
      large: "https://images.pokemontcg.io/sv6/182_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-102",
    name: "Probopass",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/102.png",
      large: "https://images.pokemontcg.io/sv6/102_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-161",
    name: "Raifort",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/161.png",
      large: "https://images.pokemontcg.io/sv6/161_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-225",
    name: "Rescue Board",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "Hyper Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/225.png",
      large: "https://images.pokemontcg.io/sv6/225_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-125",
    name: "Revavroom",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/125.png",
      large: "https://images.pokemontcg.io/sv6/125_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-16",
    name: "Rillaboom",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/16.png",
      large: "https://images.pokemontcg.io/sv6/16_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-97",
    name: "Sandshrew",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/97.png",
      large: "https://images.pokemontcg.io/sv6/97_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-98",
    name: "Sandslash",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/98.png",
      large: "https://images.pokemontcg.io/sv6/98_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-91",
    name: "Sandygast",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/91.png",
      large: "https://images.pokemontcg.io/sv6/91_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-117",
    name: "Scolipede",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/117.png",
      large: "https://images.pokemontcg.io/sv6/117_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-162",
    name: "Scoop Up Cyclone",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "ACE SPEC Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/162.png",
      large: "https://images.pokemontcg.io/sv6/162_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-94",
    name: "Scream Tail ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/94.png",
      large: "https://images.pokemontcg.io/sv6/94_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-197",
    name: "Scream Tail ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/197.png",
      large: "https://images.pokemontcg.io/sv6/197_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-45",
    name: "Seaking",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/45.png",
      large: "https://images.pokemontcg.io/sv6/45_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-163",
    name: "Secret Box",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "ACE SPEC Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/163.png",
      large: "https://images.pokemontcg.io/sv6/163_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-66",
    name: "Shinx",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/66.png",
      large: "https://images.pokemontcg.io/sv6/66_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-22",
    name: "Sinistcha",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/22.png",
      large: "https://images.pokemontcg.io/sv6/22_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-210",
    name: "Sinistcha ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Special Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/210.png",
      large: "https://images.pokemontcg.io/sv6/210_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-23",
    name: "Sinistcha ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/23.png",
      large: "https://images.pokemontcg.io/sv6/23_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-189",
    name: "Sinistcha ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/189.png",
      large: "https://images.pokemontcg.io/sv6/189_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-119",
    name: "Skarmory",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/119.png",
      large: "https://images.pokemontcg.io/sv6/119_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-28",
    name: "Slugma",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/28.png",
      large: "https://images.pokemontcg.io/sv6/28_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-90",
    name: "Slurpuff",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/90.png",
      large: "https://images.pokemontcg.io/sv6/90_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-136",
    name: "Snorlax",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/136.png",
      large: "https://images.pokemontcg.io/sv6/136_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-51",
    name: "Snorunt",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/51.png",
      large: "https://images.pokemontcg.io/sv6/51_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-4",
    name: "Spinarak",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/4.png",
      large: "https://images.pokemontcg.io/sv6/4_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-169",
    name: "Sunflora",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/169.png",
      large: "https://images.pokemontcg.io/sv6/169_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-7",
    name: "Sunflora",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/7.png",
      large: "https://images.pokemontcg.io/sv6/7_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-6",
    name: "Sunkern",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/6.png",
      large: "https://images.pokemontcg.io/sv6/6_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-164",
    name: "Survival Brace",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "ACE SPEC Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/164.png",
      large: "https://images.pokemontcg.io/sv6/164_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-140",
    name: "Swanna",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/140.png",
      large: "https://images.pokemontcg.io/sv6/140_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-89",
    name: "Swirlix",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/89.png",
      large: "https://images.pokemontcg.io/sv6/89_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-73",
    name: "Tadbulb",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/73.png",
      large: "https://images.pokemontcg.io/sv6/73_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-1",
    name: "Tangela",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/1.png",
      large: "https://images.pokemontcg.io/sv6/1_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-2",
    name: "Tangrowth",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/2.png",
      large: "https://images.pokemontcg.io/sv6/2_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-131",
    name: "Tatsugiri",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Uncommon",
    images: {
      small: "https://images.pokemontcg.io/sv6/131.png",
      large: "https://images.pokemontcg.io/sv6/131_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-186",
    name: "Tatsugiri",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/186.png",
      large: "https://images.pokemontcg.io/sv6/186_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-24",
    name: "Teal Mask Ogerpon",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/24.png",
      large: "https://images.pokemontcg.io/sv6/24_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-211",
    name: "Teal Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Special Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/211.png",
      large: "https://images.pokemontcg.io/sv6/211_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-221",
    name: "Teal Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Hyper Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/221.png",
      large: "https://images.pokemontcg.io/sv6/221_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-25",
    name: "Teal Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/25.png",
      large: "https://images.pokemontcg.io/sv6/25_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-190",
    name: "Teal Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/190.png",
      large: "https://images.pokemontcg.io/sv6/190_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-15",
    name: "Thwackey",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/15.png",
      large: "https://images.pokemontcg.io/sv6/15_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-183",
    name: "Timburr",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/183.png",
      large: "https://images.pokemontcg.io/sv6/183_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-103",
    name: "Timburr",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/103.png",
      large: "https://images.pokemontcg.io/sv6/103_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-110",
    name: "Ting-Lu",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/110.png",
      large: "https://images.pokemontcg.io/sv6/110_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-30",
    name: "Torkoal",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/30.png",
      large: "https://images.pokemontcg.io/sv6/30_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-172",
    name: "Torkoal",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/172.png",
      large: "https://images.pokemontcg.io/sv6/172_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-13",
    name: "Trevenant",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/13.png",
      large: "https://images.pokemontcg.io/sv6/13_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-165",
    name: "Unfair Stamp",
    supertype: "Trainer",
    set_name: "Twilight Masquerade",
    rarity: "ACE SPEC Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/165.png",
      large: "https://images.pokemontcg.io/sv6/165_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-124",
    name: "Varoom",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/124.png",
      large: "https://images.pokemontcg.io/sv6/124_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-115",
    name: "Venipede",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/115.png",
      large: "https://images.pokemontcg.io/sv6/115_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-9",
    name: "Volbeat",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/9.png",
      large: "https://images.pokemontcg.io/sv6/9_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-26",
    name: "Vulpix",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/26.png",
      large: "https://images.pokemontcg.io/sv6/26_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-63",
    name: "Walking Wake",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/63.png",
      large: "https://images.pokemontcg.io/sv6/63_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-178",
    name: "Wattrel",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/178.png",
      large: "https://images.pokemontcg.io/sv6/178_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-75",
    name: "Wattrel",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/75.png",
      large: "https://images.pokemontcg.io/sv6/75_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-213",
    name: "Wellspring Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Special Illustration Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/213.png",
      large: "https://images.pokemontcg.io/sv6/213_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-64",
    name: "Wellspring Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Double Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/64.png",
      large: "https://images.pokemontcg.io/sv6/64_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-194",
    name: "Wellspring Mask Ogerpon ex",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Ultra Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/194.png",
      large: "https://images.pokemontcg.io/sv6/194_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-116",
    name: "Whirlipede",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Common",
    images: {
      small: "https://images.pokemontcg.io/sv6/116.png",
      large: "https://images.pokemontcg.io/sv6/116_hires.png",
    },
    price: 20000,
  },
  {
    id: "sv6-65",
    name: "Zapdos",
    supertype: "Pokémon",
    set_name: "Twilight Masquerade",
    rarity: "Rare",
    images: {
      small: "https://images.pokemontcg.io/sv6/65.png",
      large: "https://images.pokemontcg.io/sv6/65_hires.png",
    },
    price: 20000,
  },
];
